Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SymbolArray:
  Enabled: true

Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys

Style/MethodDefParentheses:
  Enabled: false

Style/AndOr:
  Enabled: false